// npm run build:skill       copy the skill and component docs into skill/reference/
// npm run skill:install     …and install the skill at .claude/skills/noiir/ for this project
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const ref = join(root, 'skill', 'reference')

function copyDocs(from: string, to: string): string[] {
  rmSync(to, { recursive: true, force: true })
  mkdirSync(to, { recursive: true })
  const names: string[] = []
  for (const dir of readdirSync(from, { withFileTypes: true })) {
    if (!dir.isDirectory()) continue
    const md = join(from, dir.name, `${dir.name}.md`)
    if (!existsSync(md)) continue
    cpSync(md, join(to, `${dir.name}.md`))
    names.push(dir.name)
  }
  return names.sort()
}

const skills = copyDocs(join(root, 'src', 'skills'), join(ref, 'skills'))
const library = copyDocs(join(root, 'src', 'library'), join(ref, 'library'))
cpSync(join(root, 'src', 'frame', 'frame.md'), join(ref, 'frame.md'))

const title = (file: string) => readFileSync(file, 'utf8').split('\n')[0]!.replace(/^#\s*/, '')
/** The doc's first prose line: skips the title, headings, tables and code blocks. */
function firstLine(file: string): string {
  let fenced = false
  for (const line of readFileSync(file, 'utf8').split('\n').slice(1)) {
    if (line.startsWith('```')) fenced = !fenced
    else if (!fenced && line.trim() && !/^(#|\||<)/.test(line)) return line.trim()
  }
  return ''
}

writeFileSync(
  join(ref, 'index.md'),
  [
    '# noiir reference',
    '',
    'Generated by `npm run build:skill` from the `.md` files next to the code. Load only what the task touches.',
    '',
    '- [frame.md](frame.md): the Frame primitive, every prop by skill, and how styles compile',
    '',
    '## Skills (prop groups)',
    '',
    ...skills.map((s) => `- [${s}](skills/${s}.md): ${firstLine(join(ref, 'skills', `${s}.md`))}`),
    '',
    '## Library',
    '',
    ...library.map((c) => `- [${title(join(ref, 'library', `${c}.md`))}](library/${c}.md): ${firstLine(join(ref, 'library', `${c}.md`))}`),
    '',
    '## Commands',
    '',
    ...['sketch', 'build', 'convert', 'audit', 'explain'].map((c) => `- [${c}](commands/${c}.md)`),
    '',
  ].join('\n'),
)
console.log(`skill reference: ${skills.length} skills, ${library.length} library docs → skill/reference/`)

if (process.argv.includes('--install')) {
  const target = join(root, '.claude', 'skills', 'noiir')
  rmSync(target, { recursive: true, force: true })
  mkdirSync(join(root, '.claude', 'skills'), { recursive: true })
  cpSync(join(root, 'skill'), target, { recursive: true })
  console.log(`installed → ${target}`)
}
