// ── The primitive ────────────────────────────────────────────────────────────
export { Frame } from './frame/frame.view.tsx'
export { defineFrame } from './frame/define.tsx'
export type { DefinedProps, DefineInput } from './frame/define.tsx'
export type { FrameProps, Style, Slots, VariantMap } from './frame/frame.interface.ts'

// ── Skills (prop groups) ─────────────────────────────────────────────────────
export type { LayoutStyle, Flow, Align, Justify, Length } from './skills/layout/layout.interface.ts'
export type { SizeStyle, Size } from './skills/size/size.interface.ts'
export type { SpaceStyle, Space } from './skills/space/space.interface.ts'
export type { PlaceStyle } from './skills/place/place.interface.ts'
export type { PaintStyle, Paint, PaintLayer, Color, Pattern, Blend } from './skills/paint/paint.interface.ts'
export type { EdgeStyle, BorderSpec, OutlineSpec, Side } from './skills/edge/edge.interface.ts'
export type { TypeStyle, FontSpec } from './skills/type/type.interface.ts'
export type { EffectStyle, ShadowSpec } from './skills/effect/effect.interface.ts'
export type { StateProps, StateFlag } from './skills/state/state.interface.ts'
export type { MotionProps, MotionToken, LoopToken } from './skills/motion/motion.interface.ts'
export { MOTIONS, LOOPS } from './skills/motion/motion.interface.ts'
export type { InteractProps, InteractStyle, ScrollInfo, DragInfo, KeyMap } from './skills/interact/interact.interface.ts'
export type { RespondProps, AtKey } from './skills/respond/respond.interface.ts'
export type { AccessProps, Tag } from './skills/access/access.interface.ts'

// ── Actions ──────────────────────────────────────────────────────────────────
export type { Action, Actions, DataAction, Handler } from './actions/actions.interface.ts'
export { run, setNavigate, prefersReducedMotion } from './actions/run.ts'
export { emit, on } from './actions/bus.ts'

// ── Tokens and engine ────────────────────────────────────────────────────────
export { createTheme, defaultTheme, themeVars } from './tokens/createTheme.ts'
export type { Theme, ThemeInput, Tint, ColorToken, FontToken, ShadowToken, Breakpoint, TextSpec } from './tokens/tokens.interface.ts'
export { BREAKPOINTS, FONT_TOKENS } from './tokens/tokens.interface.ts'
export { COLOR_TOKENS, PALETTES, TINTS, contrast } from './tokens/palettes.ts'
export { cssText, ruleCount } from './engine/sheet.ts'
export { loadFonts, FONTS_HREF } from './tokens/fonts.ts'
export { RADIUS_TOKENS } from './tokens/tokens.interface.ts'
export type { RadiusToken, FontFamilyToken } from './tokens/tokens.interface.ts'
export type { Radius } from './skills/edge/edge.interface.ts'

// ── Standard wireframe library ───────────────────────────────────────────────
export { Screen } from './library/screen/screen.view.tsx'
export { Stack, Row, Grid, Spacer } from './library/layout/layout.view.tsx'
export { Divider } from './library/divider/divider.view.tsx'
export { Text, Link } from './library/text/text.view.tsx'
export { Placeholder } from './library/placeholder/placeholder.view.tsx'
export { Lorem } from './library/lorem/lorem.view.tsx'
export { Glyph } from './library/glyph/glyph.view.tsx'
export { GLYPHS } from './library/glyph/glyph.interface.ts'
export { Button } from './library/button/button.view.tsx'
export { Input, Field } from './library/input/input.view.tsx'
export { Textarea } from './library/textarea/textarea.view.tsx'
export { Select } from './library/select/select.view.tsx'
export { Checkbox } from './library/checkbox/checkbox.view.tsx'
export { RadioGroup } from './library/radio/radio.view.tsx'
export { Toggle } from './library/toggle/toggle.view.tsx'
export { Card } from './library/card/card.view.tsx'
export { Panel } from './library/panel/panel.view.tsx'
export { List, ListItem } from './library/list/list.view.tsx'
export { Table } from './library/table/table.view.tsx'
export { Tabs } from './library/tabs/tabs.view.tsx'
export { Menu } from './library/menu/menu.view.tsx'
export { Modal } from './library/modal/modal.view.tsx'
export { Tooltip } from './library/tooltip/tooltip.view.tsx'
export { Toaster } from './library/toast/toast.view.tsx'
export { toast } from './library/toast/toast.viewmodel.ts'
export { Progress } from './library/progress/progress.view.tsx'
export { Spinner } from './library/spinner/spinner.view.tsx'
export { Badge } from './library/badge/badge.view.tsx'
export { Cursor } from './library/cursor/cursor.view.tsx'
export * as recipes from './library/recipes.ts'

export type { ScreenProps } from './library/screen/screen.interface.ts'
export type { StackProps, RowProps, GridProps, SpacerProps } from './library/layout/layout.interface.ts'
export type { DividerProps } from './library/divider/divider.interface.ts'
export type { TextProps, LinkProps } from './library/text/text.interface.ts'
export type { PlaceholderProps, PlaceholderKind } from './library/placeholder/placeholder.interface.ts'
export type { LoremProps } from './library/lorem/lorem.interface.ts'
export type { GlyphProps, GlyphName } from './library/glyph/glyph.interface.ts'
export type { ButtonProps, ButtonKind, ButtonSize } from './library/button/button.interface.ts'
export type { InputProps, FieldProps, FieldType } from './library/input/input.interface.ts'
export type { TextareaProps } from './library/textarea/textarea.interface.ts'
export type { SelectProps, SelectOption } from './library/select/select.interface.ts'
export type { CheckboxProps } from './library/checkbox/checkbox.interface.ts'
export type { RadioGroupProps, RadioOption } from './library/radio/radio.interface.ts'
export type { ToggleProps } from './library/toggle/toggle.interface.ts'
export type { CardProps } from './library/card/card.interface.ts'
export type { PanelProps } from './library/panel/panel.interface.ts'
export type { ListProps, ListItemProps, ListMarker } from './library/list/list.interface.ts'
export type { TableProps, Column } from './library/table/table.interface.ts'
export type { TabsProps, TabItem } from './library/tabs/tabs.interface.ts'
export type { MenuProps, MenuItem } from './library/menu/menu.interface.ts'
export type { ModalProps } from './library/modal/modal.interface.ts'
export type { TooltipProps } from './library/tooltip/tooltip.interface.ts'
export type { ToasterProps, ToastKind, ToastOptions } from './library/toast/toast.interface.ts'
export type { ProgressProps } from './library/progress/progress.interface.ts'
export type { SpinnerProps } from './library/spinner/spinner.interface.ts'
export type { BadgeProps, BadgeTone } from './library/badge/badge.interface.ts'
export type { CursorProps } from './library/cursor/cursor.interface.ts'
